name: Build

on:
  push:
    branches:
    - main
    - mbedtls_ci
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
        crypto: [OPENSSL, MBEDTLS]
        exclude:
          - os: macos-11
            compiler: gcc
          - os: macos-12
            compiler: gcc
    env:
      CC: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          if [[ "${{ matrix.crypto }}" == "OPENSSL" ]]; then
            echo "OPENSSL_ROOT_DIR=/usr/local/opt/openssl" >> $GITHUB_ENV
          else
            brew install mbedtls
            echo "LDFLAGS=-L/usr/local/opt/mbedtls/lib" >> $GITHUB_ENV
          fi
        else
          if [[ "${{ matrix.crypto }}" == "MBEDTLS" ]]; then
            sudo apt update && sudo apt install -y libmbedtls-dev
          fi
        fi

        if [[ "${{ matrix.crypto }}" == "OPENSSL" ]]; then
          echo "USE_OPENSSL=yes" >> $GITHUB_ENV
          echo "USE_MBEDTLS=no" >> $GITHUB_ENV
        else
          echo "USE_OPENSSL=no" >> $GITHUB_ENV
          echo "USE_MBEDTLS=yes" >> $GITHUB_ENV
        fi

    - name: make info
      run: |
        echo "OS: ${{ matrix.os }}"
        echo "--- ${{ matrix.compiler }} DEBUG VERSION ---"
        ${{ matrix.compiler }} - --version
        echo "--- make info ---"
        make info

    - name: test re.mk
      run: make -C mk -f test.mk

    - name: make
      run: |
        make EXTRA_CFLAGS=-Werror CCACHE=

    - name: cmake
      run: |
        make cmake
        cmake --install build --prefix dist

    - uses: sreimers/pr-dependency-action@v0.5
      with:
        name: rem
        repo: https://github.com/baresip/rem
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - uses: sreimers/pr-dependency-action@v0.5
      with:
        name: retest
        repo: https://github.com/baresip/retest.git
        secret: ${{ secrets.GITHUB_TOKEN }}
        working-directory: '../.'

    - name: retest
      run: |
        set -x
        cd ..
        rm re/libre.so || true
        rm re/libre.dylib || true
        make -C rem librem.a
        echo "if(USE_MBEDTLS)" >> CMakeLists.txt
        echo "target_link_libraries(${PROJECT_NAME} PRIVATE MbedTLS MbedCrypto MbedX509)" >> CMakeLists.txt
        echo "endif()" >> CMakeLists.txt
        cd retest && make && ./retest -r
